version: '3.9'

services:
  
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .docker.env
    depends_on:
      - db
      - redis
      - celery
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    
  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .docker.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    
  redis:
    image: redis
    container_name: redis_db
    env_file:
      - .docker.env
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery_worker
    command: celery -A tasks.email_msg:celery worker --loglevel=info
    environment:
      - PYTHONPATH=/app/src
    depends_on:
      - redis

    
volumes:
  postgres_data:
