"""delete order.seller_id

Revision ID: 806ab5b6c1ac
Revises: f507d4bec1aa
Create Date: 2024-11-14 12:22:34.040361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '806ab5b6c1ac'
down_revision: Union[str, None] = 'f507d4bec1aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_seller_id_fkey', 'order', type_='foreignkey')
    op.drop_column('order', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('order_seller_id_fkey', 'order', 'user', ['seller_id'], ['id'])
    # ### end Alembic commands ###
